-- Contenu de depart global — GENERE par supabase/generate-seed.mjs depuis
-- src/data/vocab.json, grammar.json et listening.json. Ne pas editer a la main.
insert into public.content_items (id, household_id, type, theme, front, back, choices, question, difficulty, curriculum_unit) values
  ('school-01', null, 'vocab', 'Op school', 'de school', 'l''école', null, null, 1, null),
  ('school-02', null, 'vocab', 'Op school', 'het huiswerk', 'les devoirs', null, null, 1, null),
  ('school-03', null, 'vocab', 'Op school', 'de leraar', 'le professeur', null, null, 1, null),
  ('school-04', null, 'vocab', 'Op school', 'de klas', 'la classe', null, null, 1, null),
  ('school-05', null, 'vocab', 'Op school', 'het boek', 'le livre', null, null, 1, null),
  ('school-06', null, 'vocab', 'Op school', 'de pen', 'le stylo', null, null, 1, null),
  ('school-07', null, 'vocab', 'Op school', 'het examen', 'l''examen', null, null, 1, null),
  ('school-08', null, 'vocab', 'Op school', 'leren', 'apprendre, étudier', null, null, 1, null),
  ('eten-01', null, 'vocab', 'Eten en drinken', 'het brood', 'le pain', null, null, 1, null),
  ('eten-02', null, 'vocab', 'Eten en drinken', 'de kaas', 'le fromage', null, null, 1, null),
  ('eten-03', null, 'vocab', 'Eten en drinken', 'de appel', 'la pomme', null, null, 1, null),
  ('eten-04', null, 'vocab', 'Eten en drinken', 'het water', 'l''eau', null, null, 1, null),
  ('eten-05', null, 'vocab', 'Eten en drinken', 'de melk', 'le lait', null, null, 1, null),
  ('eten-06', null, 'vocab', 'Eten en drinken', 'het ontbijt', 'le petit-déjeuner', null, null, 2, null),
  ('eten-07', null, 'vocab', 'Eten en drinken', 'eten', 'manger', null, null, 1, null),
  ('eten-08', null, 'vocab', 'Eten en drinken', 'drinken', 'boire', null, null, 1, null),
  ('familie-01', null, 'vocab', 'De familie', 'de moeder', 'la mère', null, null, 1, null),
  ('familie-02', null, 'vocab', 'De familie', 'de vader', 'le père', null, null, 1, null),
  ('familie-03', null, 'vocab', 'De familie', 'de broer', 'le frère', null, null, 1, null),
  ('familie-04', null, 'vocab', 'De familie', 'de zus', 'la sœur', null, null, 1, null),
  ('familie-05', null, 'vocab', 'De familie', 'de grootouders', 'les grands-parents', null, null, 2, null),
  ('familie-06', null, 'vocab', 'De familie', 'het gezin', 'la famille (le foyer)', null, null, 2, null),
  ('familie-07', null, 'vocab', 'De familie', 'de oom', 'l''oncle', null, null, 1, null),
  ('familie-08', null, 'vocab', 'De familie', 'de tante', 'la tante', null, null, 1, null),
  ('vrijetijd-01', null, 'vocab', 'Vrije tijd', 'het spel', 'le jeu', null, null, 1, null),
  ('vrijetijd-02', null, 'vocab', 'Vrije tijd', 'de film', 'le film', null, null, 1, null),
  ('vrijetijd-03', null, 'vocab', 'Vrije tijd', 'de muziek', 'la musique', null, null, 1, null),
  ('vrijetijd-04', null, 'vocab', 'Vrije tijd', 'voetballen', 'jouer au football', null, null, 1, null),
  ('vrijetijd-05', null, 'vocab', 'Vrije tijd', 'zwemmen', 'nager', null, null, 1, null),
  ('vrijetijd-06', null, 'vocab', 'Vrije tijd', 'lezen', 'lire', null, null, 1, null),
  ('vrijetijd-07', null, 'vocab', 'Vrije tijd', 'de hobby', 'le passe-temps', null, null, 1, null),
  ('vrijetijd-08', null, 'vocab', 'Vrije tijd', 'fietsen', 'faire du vélo', null, null, 1, null),
  ('weer-01', null, 'vocab', 'Het weer', 'de zon', 'le soleil', null, null, 1, null),
  ('weer-02', null, 'vocab', 'Het weer', 'de regen', 'la pluie', null, null, 1, null),
  ('weer-03', null, 'vocab', 'Het weer', 'de wind', 'le vent', null, null, 1, null),
  ('weer-04', null, 'vocab', 'Het weer', 'de sneeuw', 'la neige', null, null, 1, null),
  ('weer-05', null, 'vocab', 'Het weer', 'het onweer', 'l''orage', null, null, 2, null),
  ('weer-06', null, 'vocab', 'Het weer', 'warm', 'chaud', null, null, 1, null),
  ('weer-07', null, 'vocab', 'Het weer', 'koud', 'froid', null, null, 1, null),
  ('weer-08', null, 'vocab', 'Het weer', 'de wolk', 'le nuage', null, null, 2, null),
  ('stad-01', null, 'vocab', 'In de stad', 'de winkel', 'le magasin', null, null, 1, null),
  ('stad-02', null, 'vocab', 'In de stad', 'de straat', 'la rue', null, null, 1, null),
  ('stad-03', null, 'vocab', 'In de stad', 'het station', 'la gare', null, null, 1, null),
  ('stad-04', null, 'vocab', 'In de stad', 'de bushalte', 'l''arrêt de bus', null, null, 2, null),
  ('stad-05', null, 'vocab', 'In de stad', 'het ziekenhuis', 'l''hôpital', null, null, 2, null),
  ('stad-06', null, 'vocab', 'In de stad', 'de markt', 'le marché', null, null, 1, null),
  ('stad-07', null, 'vocab', 'In de stad', 'links', 'à gauche', null, null, 1, null),
  ('stad-08', null, 'vocab', 'In de stad', 'rechts', 'à droite', null, null, 1, null),
  ('tijd-01', null, 'vocab', 'De tijd', 'vandaag', 'aujourd''hui', null, null, 1, null),
  ('tijd-02', null, 'vocab', 'De tijd', 'morgen', 'demain', null, null, 1, null),
  ('tijd-03', null, 'vocab', 'De tijd', 'gisteren', 'hier', null, null, 1, null),
  ('tijd-04', null, 'vocab', 'De tijd', 'de week', 'la semaine', null, null, 1, null),
  ('tijd-05', null, 'vocab', 'De tijd', 'het jaar', 'l''année', null, null, 1, null),
  ('tijd-06', null, 'vocab', 'De tijd', 'het uur', 'l''heure', null, null, 1, null),
  ('tijd-07', null, 'vocab', 'De tijd', 'de maand', 'le mois', null, null, 1, null),
  ('tijd-08', null, 'vocab', 'De tijd', 'altijd', 'toujours', null, null, 2, null),
  ('gevoel-01', null, 'vocab', 'Gevoelens', 'blij', 'content, heureux', null, null, 1, null),
  ('gevoel-02', null, 'vocab', 'Gevoelens', 'verdrietig', 'triste', null, null, 2, null),
  ('gevoel-03', null, 'vocab', 'Gevoelens', 'moe', 'fatigué', null, null, 1, null),
  ('gevoel-04', null, 'vocab', 'Gevoelens', 'bang', 'effrayé (avoir peur)', null, null, 1, null),
  ('gevoel-05', null, 'vocab', 'Gevoelens', 'boos', 'fâché', null, null, 1, null),
  ('gevoel-06', null, 'vocab', 'Gevoelens', 'ziek', 'malade', null, null, 1, null),
  ('gevoel-07', null, 'vocab', 'Gevoelens', 'graag', 'volontiers, avec plaisir', null, null, 2, null),
  ('gevoel-08', null, 'vocab', 'Gevoelens', 'leuk', 'chouette, amusant', null, null, 1, null),
  ('gram-pres-01', null, 'grammar', 'Le présent', 'Hij ___ in Brussel. (wonen)', 'woont', '["woon","woont","wonen"]'::jsonb, null, 1, null),
  ('gram-pres-02', null, 'grammar', 'Le présent', 'Ik ___ graag naar muziek. (luisteren)', 'luister', '["luister","luistert","luisteren"]'::jsonb, null, 1, null),
  ('gram-pres-03', null, 'grammar', 'Le présent', '___ jij morgen naar school? (gaan)', 'Ga', '["Ga","Gaat","Gaan"]'::jsonb, null, 2, null),
  ('gram-pres-04', null, 'grammar', 'Le présent', 'Wij ___ Nederlands op school. (leren)', 'leren', '["leer","leert","leren"]'::jsonb, null, 1, null),
  ('gram-pres-05', null, 'grammar', 'Le présent', 'Zij ___ een boek. (lezen — zij = elle)', 'leest', '["lees","leest","lezen"]'::jsonb, null, 1, null),
  ('gram-pres-06', null, 'grammar', 'Le présent', 'Jij ___ altijd te laat. (komen)', 'komt', '["kom","komt","komen"]'::jsonb, null, 1, null),
  ('gram-zijn-01', null, 'grammar', 'Hebben & zijn', 'Ik ___ veertien jaar.', 'ben', '["ben","bent","is"]'::jsonb, null, 1, null),
  ('gram-zijn-02', null, 'grammar', 'Hebben & zijn', 'Hij ___ twee zussen.', 'heeft', '["heb","hebt","heeft"]'::jsonb, null, 1, null),
  ('gram-zijn-03', null, 'grammar', 'Hebben & zijn', 'Wij ___ moe na de sportles.', 'zijn', '["ben","is","zijn"]'::jsonb, null, 1, null),
  ('gram-zijn-04', null, 'grammar', 'Hebben & zijn', '___ je een fiets?', 'Heb', '["Heb","Hebt","Heeft"]'::jsonb, null, 2, null),
  ('gram-neg-01', null, 'grammar', 'La négation (niet / geen)', 'Ik heb ___ fiets.', 'geen', '["niet","geen","nee"]'::jsonb, null, 2, null),
  ('gram-neg-02', null, 'grammar', 'La négation (niet / geen)', 'Hij komt ___ naar het feest.', 'niet', '["geen","niet","nee"]'::jsonb, null, 2, null),
  ('gram-neg-03', null, 'grammar', 'La négation (niet / geen)', 'Zij drinkt ___ koffie.', 'geen', '["niet","geen","nee"]'::jsonb, null, 2, null),
  ('gram-neg-04', null, 'grammar', 'La négation (niet / geen)', 'Wij hebben vandaag ___ huiswerk.', 'geen', '["niet","geen","nee"]'::jsonb, null, 2, null),
  ('gram-neg-05', null, 'grammar', 'La négation (niet / geen)', 'Ik begrijp de vraag ___.', 'niet', '["geen","niet","nee"]'::jsonb, null, 2, null),
  ('gram-orde-01', null, 'grammar', 'L''ordre des mots (inversion)', 'Morgen ___ naar zee.', 'gaan wij', '["wij gaan","gaan wij","gaat wij"]'::jsonb, null, 2, null),
  ('gram-orde-02', null, 'grammar', 'L''ordre des mots (inversion)', 'Vandaag ___ thuis.', 'blijf ik', '["ik blijf","blijf ik","blijft ik"]'::jsonb, null, 2, null),
  ('gram-orde-03', null, 'grammar', 'L''ordre des mots (inversion)', 'In de zomer ___ vaak in het meer.', 'zwemmen we', '["we zwemmen","zwemmen we","zwemt we"]'::jsonb, null, 2, null),
  ('gram-orde-04', null, 'grammar', 'L''ordre des mots (inversion)', 'Na school ___ mijn huiswerk.', 'maak ik', '["ik maak","maak ik","maakt ik"]'::jsonb, null, 2, null),
  ('gram-perf-01', null, 'grammar', 'Le perfectum', 'Ik ___ gisteren gevoetbald.', 'heb', '["heb","ben","hebt"]'::jsonb, null, 3, null),
  ('gram-perf-02', null, 'grammar', 'Le perfectum', 'Wij ___ naar Antwerpen gefietst.', 'zijn', '["hebben","zijn","is"]'::jsonb, null, 3, null),
  ('gram-perf-03', null, 'grammar', 'Le perfectum', 'Hij heeft een boek ___. (lezen)', 'gelezen', '["gelezen","geleest","lezen"]'::jsonb, null, 3, null),
  ('gram-perf-04', null, 'grammar', 'Le perfectum', 'Zij heeft haar huiswerk ___. (maken)', 'gemaakt', '["gemaakt","gemaakd","maken"]'::jsonb, null, 3, null),
  ('gram-perf-05', null, 'grammar', 'Le perfectum', 'Ik heb gisteravond tv ___. (kijken)', 'gekeken', '["gekeken","gekijkt","kijken"]'::jsonb, null, 3, null),
  ('gram-perf-06', null, 'grammar', 'Le perfectum', 'Wij ___ gisteren thuis gebleven.', 'zijn', '["hebben","zijn","heeft"]'::jsonb, null, 3, null),
  ('gram-modal-01', null, 'grammar', 'Les verbes modaux', 'Ik ___ goed zwemmen. (savoir / pouvoir)', 'kan', '["kan","kun","kunt"]'::jsonb, null, 2, null),
  ('gram-modal-02', null, 'grammar', 'Les verbes modaux', 'Jij ___ eerst je huiswerk maken. (devoir)', 'moet', '["moet","mag","wil"]'::jsonb, null, 2, null),
  ('gram-modal-03', null, 'grammar', 'Les verbes modaux', '___ ik naar het toilet? (demander la permission)', 'Mag', '["Mag","Moet","Wil"]'::jsonb, null, 2, null),
  ('gram-modal-04', null, 'grammar', 'Les verbes modaux', 'Wij ___ een film kijken. (vouloir)', 'willen', '["wil","willen","wilt"]'::jsonb, null, 2, null),
  ('gram-modal-05', null, 'grammar', 'Les verbes modaux', 'Hij kan vandaag niet ___. (komen — attention à la place du verbe)', 'komen', '["komt","komen","kwam"]'::jsonb, null, 2, null),
  ('gram-pron-01', null, 'grammar', 'Les pronoms', '___ woont in Gent. (il)', 'Hij', '["Hij","Hem","Zij"]'::jsonb, null, 1, null),
  ('gram-pron-02', null, 'grammar', 'Les pronoms', 'Ik zie ___ morgen. (lui)', 'hem', '["hij","hem","zij"]'::jsonb, null, 2, null),
  ('gram-pron-03', null, 'grammar', 'Les pronoms', 'Dat is ___ boek. (mon)', 'mijn', '["mijn","mij","ik"]'::jsonb, null, 1, null),
  ('gram-pron-04', null, 'grammar', 'Les pronoms', '___ fiets is rood. (sa — à elle)', 'Haar', '["Haar","Zijn","Hun"]'::jsonb, null, 2, null),
  ('gram-plur-01', null, 'grammar', 'Le pluriel', 'één boek, twee ___', 'boeken', '["boeks","boeken","boekken"]'::jsonb, null, 1, null),
  ('gram-plur-02', null, 'grammar', 'Le pluriel', 'één tafel, twee ___', 'tafels', '["tafels","tafelen","tafells"]'::jsonb, null, 1, null),
  ('gram-plur-03', null, 'grammar', 'Le pluriel', 'één kind, twee ___', 'kinderen', '["kinds","kinden","kinderen"]'::jsonb, null, 2, null),
  ('gram-vraag-01', null, 'grammar', 'Les mots interrogatifs', '___ woon je? — In Luik.', 'Waar', '["Waar","Wanneer","Wie"]'::jsonb, null, 1, null),
  ('gram-vraag-02', null, 'grammar', 'Les mots interrogatifs', '___ oud ben je?', 'Hoe', '["Hoe","Wat","Waar"]'::jsonb, null, 1, null),
  ('gram-vraag-03', null, 'grammar', 'Les mots interrogatifs', '___ kom je niet? — Omdat ik ziek ben.', 'Waarom', '["Waarom","Wanneer","Waar"]'::jsonb, null, 2, null),
  ('gram-vraag-04', null, 'grammar', 'Les mots interrogatifs', '___ is dat meisje? — Mijn zus.', 'Wie', '["Wie","Wat","Waar"]'::jsonb, null, 1, null),
  ('lis-01', null, 'listening', 'Se présenter', 'Hallo, ik heet Emma. Ik ben dertien jaar en ik woon in Gent.', '13 ans', '["12 ans","13 ans","30 ans"]'::jsonb, 'Quel âge a Emma ?', 1, null),
  ('lis-02', null, 'listening', 'La famille', 'Mijn broer werkt in een winkel in Antwerpen.', 'dans un magasin', '["dans un magasin","dans une école","dans un hôpital"]'::jsonb, 'Où travaille le frère ?', 1, null),
  ('lis-03', null, 'listening', 'Les déplacements', 'We gaan zaterdag met de trein naar zee.', 'en train', '["en train","en voiture","à vélo"]'::jsonb, 'Comment vont-ils à la mer ?', 1, null),
  ('lis-04', null, 'listening', 'La météo', 'Het is vandaag koud en het regent.', 'froid et pluvieux', '["froid et pluvieux","chaud et ensoleillé","il neige"]'::jsonb, 'Quel temps fait-il aujourd''hui ?', 1, null),
  ('lis-05', null, 'listening', 'Les loisirs', 'De film begint om acht uur.', 'à 8 h', '["à 8 h","à 10 h","à 18 h"]'::jsonb, 'À quelle heure commence le film ?', 1, null),
  ('lis-06', null, 'listening', 'Au restaurant', 'Ik wil graag twee broodjes met kaas, alstublieft.', '2 sandwichs au fromage', '["2 sandwichs au fromage","2 sandwichs au jambon","1 sandwich au fromage"]'::jsonb, 'Que commande-t-il ?', 2, null),
  ('lis-07', null, 'listening', 'Les loisirs', 'Mijn zus speelt elke woensdag tennis.', 'du tennis', '["du tennis","du football","de la natation"]'::jsonb, 'Que fait la sœur le mercredi ?', 1, null),
  ('lis-08', null, 'listening', 'En ville', 'De bibliotheek is naast het station.', 'à côté de la gare', '["à côté de la gare","derrière l''école","en face du parc"]'::jsonb, 'Où est la bibliothèque ?', 2, null),
  ('lis-09', null, 'listening', 'La routine', 'Ik sta elke dag om zeven uur op.', 'à 7 h', '["à 7 h","à 6 h","à 8 h"]'::jsonb, 'À quelle heure se lève-t-il ?', 1, null),
  ('lis-10', null, 'listening', 'Manger et boire', 'Wij eten vanavond frietjes met vis.', 'des frites avec du poisson', '["des frites avec du poisson","des frites avec du poulet","de la soupe"]'::jsonb, 'Que mangent-ils ce soir ?', 1, null),
  ('lis-11', null, 'listening', 'Se présenter', 'Mijn lievelingskleur is groen.', 'le vert', '["le vert","le rouge","le jaune"]'::jsonb, 'Quelle est sa couleur préférée ?', 1, null),
  ('lis-12', null, 'listening', 'Les déplacements', 'De bus naar Brussel vertrekt over tien minuten.', 'dans 10 minutes', '["dans 10 minutes","dans 5 minutes","dans une heure"]'::jsonb, 'Quand part le bus pour Bruxelles ?', 2, null),
  ('lis-13', null, 'listening', 'Au quotidien', 'Ik kan niet komen, want ik ben ziek.', 'il est malade', '["il est malade","il est fatigué","il doit travailler"]'::jsonb, 'Pourquoi ne vient-il pas ?', 2, null),
  ('lis-14', null, 'listening', 'Faire les courses', 'Hoeveel kost dat boek? — Het kost twaalf euro.', '12 €', '["12 €","2 €","20 €"]'::jsonb, 'Combien coûte le livre ?', 2, null),
  ('lis-15', null, 'listening', 'La famille', 'Mijn vader kookt elke zondag spaghetti.', 'il cuisine des spaghettis', '["il cuisine des spaghettis","il lave la voiture","il joue au football"]'::jsonb, 'Que fait le père le dimanche ?', 1, null),
  ('lis-16', null, 'listening', 'À l''école', 'Volgende week hebben we een toets Nederlands.', 'un test de néerlandais', '["un test de néerlandais","une fête à l''école","un match de football"]'::jsonb, 'Qu''y a-t-il la semaine prochaine ?', 2, null),
  ('lis-17', null, 'listening', 'Au quotidien', 'Ik zoek mijn sleutels. Heb jij ze gezien?', 'ses clés', '["ses clés","son GSM","son sac"]'::jsonb, 'Que cherche la personne ?', 2, null),
  ('lis-18', null, 'listening', 'Les loisirs', 'Het zwembad is op maandag gesloten.', 'le lundi', '["le lundi","le mardi","le week-end"]'::jsonb, 'Quand la piscine est-elle fermée ?', 1, null),
  ('lis-19', null, 'listening', 'La famille', 'Mijn oma heeft drie katten en een hond.', '3 chats et 1 chien', '["3 chats et 1 chien","1 chat et 3 chiens","2 chats et 2 chiens"]'::jsonb, 'Quels animaux a la grand-mère ?', 2, null),
  ('lis-20', null, 'listening', 'Les déplacements', 'We vertrekken morgen heel vroeg, om zes uur al.', 'demain à 6 h', '["demain à 6 h","demain à 16 h","ce soir à 6 h"]'::jsonb, 'Quand partent-ils ?', 3, null),
  ('lis-21', null, 'listening', 'Au quotidien', 'Sorry, ik versta u niet goed. Kunt u dat herhalen?', 'de répéter', '["de répéter","de parler plus vite","d''écrire le mot"]'::jsonb, 'Que demande la personne ?', 3, null),
  ('lis-22', null, 'listening', 'Les vacances', 'In de zomer ga ik twee weken naar Spanje.', '2 semaines', '["2 semaines","2 mois","2 jours"]'::jsonb, 'Combien de temps part-il en Espagne ?', 2, null),
  ('lis-23', null, 'listening', 'En ville', 'Je mag hier niet fietsen, dat is verboden.', 'faire du vélo', '["faire du vélo","marcher","jouer au ballon"]'::jsonb, 'Qu''est-ce qui est interdit ici ?', 2, null),
  ('lis-24', null, 'listening', 'À l''école', 'Mijn beste vriend heet Lucas en hij zit in mijn klas.', 'son meilleur ami', '["son meilleur ami","son frère","son professeur"]'::jsonb, 'Qui est Lucas ?', 1, null)
on conflict (id) do update set
  type = excluded.type,
  theme = excluded.theme,
  front = excluded.front,
  back = excluded.back,
  choices = excluded.choices,
  question = excluded.question,
  difficulty = excluded.difficulty,
  curriculum_unit = excluded.curriculum_unit;
