-- Contenu de depart global — GENERE par supabase/generate-seed.mjs depuis
-- src/data/vocab.json et src/data/grammar.json. Ne pas editer a la main.
insert into public.content_items (id, household_id, type, theme, front, back, choices, difficulty, curriculum_unit) values
  ('school-01', null, 'vocab', 'Op school', 'de school', 'l''école', null, 1, null),
  ('school-02', null, 'vocab', 'Op school', 'het huiswerk', 'les devoirs', null, 1, null),
  ('school-03', null, 'vocab', 'Op school', 'de leraar', 'le professeur', null, 1, null),
  ('school-04', null, 'vocab', 'Op school', 'de klas', 'la classe', null, 1, null),
  ('school-05', null, 'vocab', 'Op school', 'het boek', 'le livre', null, 1, null),
  ('school-06', null, 'vocab', 'Op school', 'de pen', 'le stylo', null, 1, null),
  ('school-07', null, 'vocab', 'Op school', 'het examen', 'l''examen', null, 1, null),
  ('school-08', null, 'vocab', 'Op school', 'leren', 'apprendre, étudier', null, 1, null),
  ('eten-01', null, 'vocab', 'Eten en drinken', 'het brood', 'le pain', null, 1, null),
  ('eten-02', null, 'vocab', 'Eten en drinken', 'de kaas', 'le fromage', null, 1, null),
  ('eten-03', null, 'vocab', 'Eten en drinken', 'de appel', 'la pomme', null, 1, null),
  ('eten-04', null, 'vocab', 'Eten en drinken', 'het water', 'l''eau', null, 1, null),
  ('eten-05', null, 'vocab', 'Eten en drinken', 'de melk', 'le lait', null, 1, null),
  ('eten-06', null, 'vocab', 'Eten en drinken', 'het ontbijt', 'le petit-déjeuner', null, 2, null),
  ('eten-07', null, 'vocab', 'Eten en drinken', 'eten', 'manger', null, 1, null),
  ('eten-08', null, 'vocab', 'Eten en drinken', 'drinken', 'boire', null, 1, null),
  ('familie-01', null, 'vocab', 'De familie', 'de moeder', 'la mère', null, 1, null),
  ('familie-02', null, 'vocab', 'De familie', 'de vader', 'le père', null, 1, null),
  ('familie-03', null, 'vocab', 'De familie', 'de broer', 'le frère', null, 1, null),
  ('familie-04', null, 'vocab', 'De familie', 'de zus', 'la sœur', null, 1, null),
  ('familie-05', null, 'vocab', 'De familie', 'de grootouders', 'les grands-parents', null, 2, null),
  ('familie-06', null, 'vocab', 'De familie', 'het gezin', 'la famille (le foyer)', null, 2, null),
  ('familie-07', null, 'vocab', 'De familie', 'de oom', 'l''oncle', null, 1, null),
  ('familie-08', null, 'vocab', 'De familie', 'de tante', 'la tante', null, 1, null),
  ('vrijetijd-01', null, 'vocab', 'Vrije tijd', 'het spel', 'le jeu', null, 1, null),
  ('vrijetijd-02', null, 'vocab', 'Vrije tijd', 'de film', 'le film', null, 1, null),
  ('vrijetijd-03', null, 'vocab', 'Vrije tijd', 'de muziek', 'la musique', null, 1, null),
  ('vrijetijd-04', null, 'vocab', 'Vrije tijd', 'voetballen', 'jouer au football', null, 1, null),
  ('vrijetijd-05', null, 'vocab', 'Vrije tijd', 'zwemmen', 'nager', null, 1, null),
  ('vrijetijd-06', null, 'vocab', 'Vrije tijd', 'lezen', 'lire', null, 1, null),
  ('vrijetijd-07', null, 'vocab', 'Vrije tijd', 'de hobby', 'le passe-temps', null, 1, null),
  ('vrijetijd-08', null, 'vocab', 'Vrije tijd', 'fietsen', 'faire du vélo', null, 1, null),
  ('weer-01', null, 'vocab', 'Het weer', 'de zon', 'le soleil', null, 1, null),
  ('weer-02', null, 'vocab', 'Het weer', 'de regen', 'la pluie', null, 1, null),
  ('weer-03', null, 'vocab', 'Het weer', 'de wind', 'le vent', null, 1, null),
  ('weer-04', null, 'vocab', 'Het weer', 'de sneeuw', 'la neige', null, 1, null),
  ('weer-05', null, 'vocab', 'Het weer', 'het onweer', 'l''orage', null, 2, null),
  ('weer-06', null, 'vocab', 'Het weer', 'warm', 'chaud', null, 1, null),
  ('weer-07', null, 'vocab', 'Het weer', 'koud', 'froid', null, 1, null),
  ('weer-08', null, 'vocab', 'Het weer', 'de wolk', 'le nuage', null, 2, null),
  ('stad-01', null, 'vocab', 'In de stad', 'de winkel', 'le magasin', null, 1, null),
  ('stad-02', null, 'vocab', 'In de stad', 'de straat', 'la rue', null, 1, null),
  ('stad-03', null, 'vocab', 'In de stad', 'het station', 'la gare', null, 1, null),
  ('stad-04', null, 'vocab', 'In de stad', 'de bushalte', 'l''arrêt de bus', null, 2, null),
  ('stad-05', null, 'vocab', 'In de stad', 'het ziekenhuis', 'l''hôpital', null, 2, null),
  ('stad-06', null, 'vocab', 'In de stad', 'de markt', 'le marché', null, 1, null),
  ('stad-07', null, 'vocab', 'In de stad', 'links', 'à gauche', null, 1, null),
  ('stad-08', null, 'vocab', 'In de stad', 'rechts', 'à droite', null, 1, null),
  ('tijd-01', null, 'vocab', 'De tijd', 'vandaag', 'aujourd''hui', null, 1, null),
  ('tijd-02', null, 'vocab', 'De tijd', 'morgen', 'demain', null, 1, null),
  ('tijd-03', null, 'vocab', 'De tijd', 'gisteren', 'hier', null, 1, null),
  ('tijd-04', null, 'vocab', 'De tijd', 'de week', 'la semaine', null, 1, null),
  ('tijd-05', null, 'vocab', 'De tijd', 'het jaar', 'l''année', null, 1, null),
  ('tijd-06', null, 'vocab', 'De tijd', 'het uur', 'l''heure', null, 1, null),
  ('tijd-07', null, 'vocab', 'De tijd', 'de maand', 'le mois', null, 1, null),
  ('tijd-08', null, 'vocab', 'De tijd', 'altijd', 'toujours', null, 2, null),
  ('gevoel-01', null, 'vocab', 'Gevoelens', 'blij', 'content, heureux', null, 1, null),
  ('gevoel-02', null, 'vocab', 'Gevoelens', 'verdrietig', 'triste', null, 2, null),
  ('gevoel-03', null, 'vocab', 'Gevoelens', 'moe', 'fatigué', null, 1, null),
  ('gevoel-04', null, 'vocab', 'Gevoelens', 'bang', 'effrayé (avoir peur)', null, 1, null),
  ('gevoel-05', null, 'vocab', 'Gevoelens', 'boos', 'fâché', null, 1, null),
  ('gevoel-06', null, 'vocab', 'Gevoelens', 'ziek', 'malade', null, 1, null),
  ('gevoel-07', null, 'vocab', 'Gevoelens', 'graag', 'volontiers, avec plaisir', null, 2, null),
  ('gevoel-08', null, 'vocab', 'Gevoelens', 'leuk', 'chouette, amusant', null, 1, null),
  ('gram-pres-01', null, 'grammar', 'Le présent', 'Hij ___ in Brussel. (wonen)', 'woont', '["woon","woont","wonen"]'::jsonb, 1, null),
  ('gram-pres-02', null, 'grammar', 'Le présent', 'Ik ___ graag naar muziek. (luisteren)', 'luister', '["luister","luistert","luisteren"]'::jsonb, 1, null),
  ('gram-pres-03', null, 'grammar', 'Le présent', '___ jij morgen naar school? (gaan)', 'Ga', '["Ga","Gaat","Gaan"]'::jsonb, 2, null),
  ('gram-pres-04', null, 'grammar', 'Le présent', 'Wij ___ Nederlands op school. (leren)', 'leren', '["leer","leert","leren"]'::jsonb, 1, null),
  ('gram-pres-05', null, 'grammar', 'Le présent', 'Zij ___ een boek. (lezen — zij = elle)', 'leest', '["lees","leest","lezen"]'::jsonb, 1, null),
  ('gram-pres-06', null, 'grammar', 'Le présent', 'Jij ___ altijd te laat. (komen)', 'komt', '["kom","komt","komen"]'::jsonb, 1, null),
  ('gram-zijn-01', null, 'grammar', 'Hebben & zijn', 'Ik ___ veertien jaar.', 'ben', '["ben","bent","is"]'::jsonb, 1, null),
  ('gram-zijn-02', null, 'grammar', 'Hebben & zijn', 'Hij ___ twee zussen.', 'heeft', '["heb","hebt","heeft"]'::jsonb, 1, null),
  ('gram-zijn-03', null, 'grammar', 'Hebben & zijn', 'Wij ___ moe na de sportles.', 'zijn', '["ben","is","zijn"]'::jsonb, 1, null),
  ('gram-zijn-04', null, 'grammar', 'Hebben & zijn', '___ je een fiets?', 'Heb', '["Heb","Hebt","Heeft"]'::jsonb, 2, null),
  ('gram-neg-01', null, 'grammar', 'La négation (niet / geen)', 'Ik heb ___ fiets.', 'geen', '["niet","geen","nee"]'::jsonb, 2, null),
  ('gram-neg-02', null, 'grammar', 'La négation (niet / geen)', 'Hij komt ___ naar het feest.', 'niet', '["geen","niet","nee"]'::jsonb, 2, null),
  ('gram-neg-03', null, 'grammar', 'La négation (niet / geen)', 'Zij drinkt ___ koffie.', 'geen', '["niet","geen","nee"]'::jsonb, 2, null),
  ('gram-neg-04', null, 'grammar', 'La négation (niet / geen)', 'Wij hebben vandaag ___ huiswerk.', 'geen', '["niet","geen","nee"]'::jsonb, 2, null),
  ('gram-neg-05', null, 'grammar', 'La négation (niet / geen)', 'Ik begrijp de vraag ___.', 'niet', '["geen","niet","nee"]'::jsonb, 2, null),
  ('gram-orde-01', null, 'grammar', 'L''ordre des mots (inversion)', 'Morgen ___ naar zee.', 'gaan wij', '["wij gaan","gaan wij","gaat wij"]'::jsonb, 2, null),
  ('gram-orde-02', null, 'grammar', 'L''ordre des mots (inversion)', 'Vandaag ___ thuis.', 'blijf ik', '["ik blijf","blijf ik","blijft ik"]'::jsonb, 2, null),
  ('gram-orde-03', null, 'grammar', 'L''ordre des mots (inversion)', 'In de zomer ___ vaak in het meer.', 'zwemmen we', '["we zwemmen","zwemmen we","zwemt we"]'::jsonb, 2, null),
  ('gram-orde-04', null, 'grammar', 'L''ordre des mots (inversion)', 'Na school ___ mijn huiswerk.', 'maak ik', '["ik maak","maak ik","maakt ik"]'::jsonb, 2, null),
  ('gram-perf-01', null, 'grammar', 'Le perfectum', 'Ik ___ gisteren gevoetbald.', 'heb', '["heb","ben","hebt"]'::jsonb, 3, null),
  ('gram-perf-02', null, 'grammar', 'Le perfectum', 'Wij ___ naar Antwerpen gefietst.', 'zijn', '["hebben","zijn","is"]'::jsonb, 3, null),
  ('gram-perf-03', null, 'grammar', 'Le perfectum', 'Hij heeft een boek ___. (lezen)', 'gelezen', '["gelezen","geleest","lezen"]'::jsonb, 3, null),
  ('gram-perf-04', null, 'grammar', 'Le perfectum', 'Zij heeft haar huiswerk ___. (maken)', 'gemaakt', '["gemaakt","gemaakd","maken"]'::jsonb, 3, null),
  ('gram-perf-05', null, 'grammar', 'Le perfectum', 'Ik heb gisteravond tv ___. (kijken)', 'gekeken', '["gekeken","gekijkt","kijken"]'::jsonb, 3, null),
  ('gram-perf-06', null, 'grammar', 'Le perfectum', 'Wij ___ gisteren thuis gebleven.', 'zijn', '["hebben","zijn","heeft"]'::jsonb, 3, null),
  ('gram-modal-01', null, 'grammar', 'Les verbes modaux', 'Ik ___ goed zwemmen. (savoir / pouvoir)', 'kan', '["kan","kun","kunt"]'::jsonb, 2, null),
  ('gram-modal-02', null, 'grammar', 'Les verbes modaux', 'Jij ___ eerst je huiswerk maken. (devoir)', 'moet', '["moet","mag","wil"]'::jsonb, 2, null),
  ('gram-modal-03', null, 'grammar', 'Les verbes modaux', '___ ik naar het toilet? (demander la permission)', 'Mag', '["Mag","Moet","Wil"]'::jsonb, 2, null),
  ('gram-modal-04', null, 'grammar', 'Les verbes modaux', 'Wij ___ een film kijken. (vouloir)', 'willen', '["wil","willen","wilt"]'::jsonb, 2, null),
  ('gram-modal-05', null, 'grammar', 'Les verbes modaux', 'Hij kan vandaag niet ___. (komen — attention à la place du verbe)', 'komen', '["komt","komen","kwam"]'::jsonb, 2, null),
  ('gram-pron-01', null, 'grammar', 'Les pronoms', '___ woont in Gent. (il)', 'Hij', '["Hij","Hem","Zij"]'::jsonb, 1, null),
  ('gram-pron-02', null, 'grammar', 'Les pronoms', 'Ik zie ___ morgen. (lui)', 'hem', '["hij","hem","zij"]'::jsonb, 2, null),
  ('gram-pron-03', null, 'grammar', 'Les pronoms', 'Dat is ___ boek. (mon)', 'mijn', '["mijn","mij","ik"]'::jsonb, 1, null),
  ('gram-pron-04', null, 'grammar', 'Les pronoms', '___ fiets is rood. (sa — à elle)', 'Haar', '["Haar","Zijn","Hun"]'::jsonb, 2, null),
  ('gram-plur-01', null, 'grammar', 'Le pluriel', 'één boek, twee ___', 'boeken', '["boeks","boeken","boekken"]'::jsonb, 1, null),
  ('gram-plur-02', null, 'grammar', 'Le pluriel', 'één tafel, twee ___', 'tafels', '["tafels","tafelen","tafells"]'::jsonb, 1, null),
  ('gram-plur-03', null, 'grammar', 'Le pluriel', 'één kind, twee ___', 'kinderen', '["kinds","kinden","kinderen"]'::jsonb, 2, null),
  ('gram-vraag-01', null, 'grammar', 'Les mots interrogatifs', '___ woon je? — In Luik.', 'Waar', '["Waar","Wanneer","Wie"]'::jsonb, 1, null),
  ('gram-vraag-02', null, 'grammar', 'Les mots interrogatifs', '___ oud ben je?', 'Hoe', '["Hoe","Wat","Waar"]'::jsonb, 1, null),
  ('gram-vraag-03', null, 'grammar', 'Les mots interrogatifs', '___ kom je niet? — Omdat ik ziek ben.', 'Waarom', '["Waarom","Wanneer","Waar"]'::jsonb, 2, null),
  ('gram-vraag-04', null, 'grammar', 'Les mots interrogatifs', '___ is dat meisje? — Mijn zus.', 'Wie', '["Wie","Wat","Waar"]'::jsonb, 1, null)
on conflict (id) do update set
  type = excluded.type,
  theme = excluded.theme,
  front = excluded.front,
  back = excluded.back,
  choices = excluded.choices,
  difficulty = excluded.difficulty,
  curriculum_unit = excluded.curriculum_unit;
