-- Contenu de depart global (genere depuis src/data/vocab.json — ne pas editer a la main,
-- regenerer via le script du README de supabase/).
insert into public.content_items (id, household_id, type, theme, front, back, difficulty, curriculum_unit) values
  ('school-01', null, 'vocab', 'Op school', 'de school', 'l''école', 1, null),
  ('school-02', null, 'vocab', 'Op school', 'het huiswerk', 'les devoirs', 1, null),
  ('school-03', null, 'vocab', 'Op school', 'de leraar', 'le professeur', 1, null),
  ('school-04', null, 'vocab', 'Op school', 'de klas', 'la classe', 1, null),
  ('school-05', null, 'vocab', 'Op school', 'het boek', 'le livre', 1, null),
  ('school-06', null, 'vocab', 'Op school', 'de pen', 'le stylo', 1, null),
  ('school-07', null, 'vocab', 'Op school', 'het examen', 'l''examen', 1, null),
  ('school-08', null, 'vocab', 'Op school', 'leren', 'apprendre, étudier', 1, null),
  ('eten-01', null, 'vocab', 'Eten en drinken', 'het brood', 'le pain', 1, null),
  ('eten-02', null, 'vocab', 'Eten en drinken', 'de kaas', 'le fromage', 1, null),
  ('eten-03', null, 'vocab', 'Eten en drinken', 'de appel', 'la pomme', 1, null),
  ('eten-04', null, 'vocab', 'Eten en drinken', 'het water', 'l''eau', 1, null),
  ('eten-05', null, 'vocab', 'Eten en drinken', 'de melk', 'le lait', 1, null),
  ('eten-06', null, 'vocab', 'Eten en drinken', 'het ontbijt', 'le petit-déjeuner', 2, null),
  ('eten-07', null, 'vocab', 'Eten en drinken', 'eten', 'manger', 1, null),
  ('eten-08', null, 'vocab', 'Eten en drinken', 'drinken', 'boire', 1, null),
  ('familie-01', null, 'vocab', 'De familie', 'de moeder', 'la mère', 1, null),
  ('familie-02', null, 'vocab', 'De familie', 'de vader', 'le père', 1, null),
  ('familie-03', null, 'vocab', 'De familie', 'de broer', 'le frère', 1, null),
  ('familie-04', null, 'vocab', 'De familie', 'de zus', 'la sœur', 1, null),
  ('familie-05', null, 'vocab', 'De familie', 'de grootouders', 'les grands-parents', 2, null),
  ('familie-06', null, 'vocab', 'De familie', 'het gezin', 'la famille (le foyer)', 2, null),
  ('familie-07', null, 'vocab', 'De familie', 'de oom', 'l''oncle', 1, null),
  ('familie-08', null, 'vocab', 'De familie', 'de tante', 'la tante', 1, null),
  ('vrijetijd-01', null, 'vocab', 'Vrije tijd', 'het spel', 'le jeu', 1, null),
  ('vrijetijd-02', null, 'vocab', 'Vrije tijd', 'de film', 'le film', 1, null),
  ('vrijetijd-03', null, 'vocab', 'Vrije tijd', 'de muziek', 'la musique', 1, null),
  ('vrijetijd-04', null, 'vocab', 'Vrije tijd', 'voetballen', 'jouer au football', 1, null),
  ('vrijetijd-05', null, 'vocab', 'Vrije tijd', 'zwemmen', 'nager', 1, null),
  ('vrijetijd-06', null, 'vocab', 'Vrije tijd', 'lezen', 'lire', 1, null),
  ('vrijetijd-07', null, 'vocab', 'Vrije tijd', 'de hobby', 'le passe-temps', 1, null),
  ('vrijetijd-08', null, 'vocab', 'Vrije tijd', 'fietsen', 'faire du vélo', 1, null),
  ('weer-01', null, 'vocab', 'Het weer', 'de zon', 'le soleil', 1, null),
  ('weer-02', null, 'vocab', 'Het weer', 'de regen', 'la pluie', 1, null),
  ('weer-03', null, 'vocab', 'Het weer', 'de wind', 'le vent', 1, null),
  ('weer-04', null, 'vocab', 'Het weer', 'de sneeuw', 'la neige', 1, null),
  ('weer-05', null, 'vocab', 'Het weer', 'het onweer', 'l''orage', 2, null),
  ('weer-06', null, 'vocab', 'Het weer', 'warm', 'chaud', 1, null),
  ('weer-07', null, 'vocab', 'Het weer', 'koud', 'froid', 1, null),
  ('weer-08', null, 'vocab', 'Het weer', 'de wolk', 'le nuage', 2, null),
  ('stad-01', null, 'vocab', 'In de stad', 'de winkel', 'le magasin', 1, null),
  ('stad-02', null, 'vocab', 'In de stad', 'de straat', 'la rue', 1, null),
  ('stad-03', null, 'vocab', 'In de stad', 'het station', 'la gare', 1, null),
  ('stad-04', null, 'vocab', 'In de stad', 'de bushalte', 'l''arrêt de bus', 2, null),
  ('stad-05', null, 'vocab', 'In de stad', 'het ziekenhuis', 'l''hôpital', 2, null),
  ('stad-06', null, 'vocab', 'In de stad', 'de markt', 'le marché', 1, null),
  ('stad-07', null, 'vocab', 'In de stad', 'links', 'à gauche', 1, null),
  ('stad-08', null, 'vocab', 'In de stad', 'rechts', 'à droite', 1, null),
  ('tijd-01', null, 'vocab', 'De tijd', 'vandaag', 'aujourd''hui', 1, null),
  ('tijd-02', null, 'vocab', 'De tijd', 'morgen', 'demain', 1, null),
  ('tijd-03', null, 'vocab', 'De tijd', 'gisteren', 'hier', 1, null),
  ('tijd-04', null, 'vocab', 'De tijd', 'de week', 'la semaine', 1, null),
  ('tijd-05', null, 'vocab', 'De tijd', 'het jaar', 'l''année', 1, null),
  ('tijd-06', null, 'vocab', 'De tijd', 'het uur', 'l''heure', 1, null),
  ('tijd-07', null, 'vocab', 'De tijd', 'de maand', 'le mois', 1, null),
  ('tijd-08', null, 'vocab', 'De tijd', 'altijd', 'toujours', 2, null),
  ('gevoel-01', null, 'vocab', 'Gevoelens', 'blij', 'content, heureux', 1, null),
  ('gevoel-02', null, 'vocab', 'Gevoelens', 'verdrietig', 'triste', 2, null),
  ('gevoel-03', null, 'vocab', 'Gevoelens', 'moe', 'fatigué', 1, null),
  ('gevoel-04', null, 'vocab', 'Gevoelens', 'bang', 'effrayé (avoir peur)', 1, null),
  ('gevoel-05', null, 'vocab', 'Gevoelens', 'boos', 'fâché', 1, null),
  ('gevoel-06', null, 'vocab', 'Gevoelens', 'ziek', 'malade', 1, null),
  ('gevoel-07', null, 'vocab', 'Gevoelens', 'graag', 'volontiers, avec plaisir', 2, null),
  ('gevoel-08', null, 'vocab', 'Gevoelens', 'leuk', 'chouette, amusant', 1, null)
on conflict (id) do update set theme = excluded.theme, front = excluded.front, back = excluded.back, difficulty = excluded.difficulty, curriculum_unit = excluded.curriculum_unit;
